### ISSUE TITLE
Vue3-ui and Buefy

### ISSUE THREAD

**Issue by Nemesis19** [pathscale/vue3-ui#3]
Dear developer,

I'm seeing a lot similarities in code with Buefy, like for example the Sidebar https://github.com/pathscale/vue3-ui/blob/master/src/components/primitives/Sidebar/Sidebar.vue...

So why should I use this lib instead of Buefy? Only for the Vue3 support?

Why don't you contact the Buefy maintainer to help develop the Vue3 version?

Thanks.

**Comment by skaptox** [comment]
Hi @Nemesis19, thanks for contact us. We had been using Buefy in some Vue 2 projects but when the Vue 3 beta versions were released we started migrating some fresh projects and the faster way for doing was try to adapte it it ASAP. We needed full flexibility and we ported it step by step.
